// Wave 2 AC1: the globe's country polygons (hub/geo/countries-110m.json) are complete,
// coded and small. Written before the globe; the file is generated by scripts/build-geo.mjs.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, statSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FILE = path.join(ROOT, 'hub/geo/countries-110m.json');

test('AC1: at least 170 features, each with an ISO alpha-2 code and English and Spanish names', () => {
  const geo = JSON.parse(readFileSync(FILE, 'utf8'));
  assert.equal(geo.type, 'FeatureCollection');
  assert.ok(geo.features.length >= 170, `only ${geo.features.length} features`);
  for (const f of geo.features) {
    assert.match(f.properties.iso2, /^[A-Z]{2}$/, JSON.stringify(f.properties));
    assert.ok(f.properties.en && f.properties.es, JSON.stringify(f.properties));
    assert.ok(f.geometry.type === 'Polygon' || f.geometry.type === 'MultiPolygon');
  }
});

test('AC1: France, Norway and Kosovo carry real codes; Colombia, Kazakhstan and Venezuela are present with Spanish names', () => {
  const geo = JSON.parse(readFileSync(FILE, 'utf8'));
  const by = new Map(geo.features.map((f) => [f.properties.iso2, f.properties]));
  assert.equal(by.get('FR').en, 'France');
  assert.equal(by.get('NO').en, 'Norway');
  assert.equal(by.get('XK').en, 'Kosovo');
  assert.equal(by.get('CO').es, 'Colombia');
  assert.equal(by.get('KZ').es, 'Kazajistán');
  assert.equal(by.get('VE').en, 'Venezuela');
  assert.ok(!geo.features.some((f) => f.properties.iso2 === '-9'));
});

test('AC1: the file is under 400 KB and coordinates are rounded to two decimals', () => {
  assert.ok(statSync(FILE).size < 400 * 1024, `${statSync(FILE).size} bytes`);
  const geo = JSON.parse(readFileSync(FILE, 'utf8'));
  const walk = (c) => (typeof c[0] === 'number' ? [c] : c.flatMap(walk));
  for (const f of geo.features) for (const [x, y] of walk(f.geometry.coordinates)) {
    assert.equal(x, Math.round(x * 100) / 100); assert.equal(y, Math.round(y * 100) / 100);
    assert.ok(Math.abs(x) <= 180 && Math.abs(y) <= 90);
  }
});
