import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { openDb } from '../src/db/client.ts';
import { migrate } from '../src/db/migrate.ts';
import { seedMaster } from '../src/db/seed.ts';
import { INDEX_MAX_LINES, regenerateLessonsIndex, renderLessonsIndex, insertLesson, type LessonRecord } from '../src/jobs/lessons-index.ts';

const NOW = new Date('2026-09-29T12:00:00Z');
const U = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const FIRM_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../firm');
const DISCIPLINES = ['reservoir', 'geology', 'petrophysics', 'commercial', 'production'];

const mk = (n: number, over: Partial<LessonRecord> = {}): LessonRecord => ({
  id: U(n), claim: `Claim number ${n} about ${DISCIPLINES[n % DISCIPLINES.length]} practice.`, scope: 'firm', scope_id: null, disciplines: [DISCIPLINES[n % DISCIPLINES.length]],
  legal_tag: 'lt-firm', sanitised: false, evidence: [`run:${U(9000 + n)}`], author: 'chris', created_at: '2026-06-01T00:00:00Z', status: 'confirmed', confirmed_by: 'chris',
  last_confirmed: '2026-09-01T00:00:00Z', valid_to: null, superseded_by: null, confidence: 0.5 + (n % 5) / 10, recurrence: 1, ...over,
});
const LINE = /^- .+ \(lesson:[0-9a-f-]{36}, [a-z]+(:[^)\s]+)?\)$/;

test('the committed initial LESSONS.md is exactly what the generator writes for an empty vault', () => {
  const committed = readFileSync(path.join(FIRM_DIR, 'LESSONS.md'), 'utf8');
  assert.equal(committed, renderLessonsIndex([], NOW).markdown);
  assert.match(committed, /Generated by vault\/src\/jobs\/lessons-index\.ts/);
  assert.match(committed, /Do not edit by hand/);
});

test('rendering groups by discipline, one line per claim with its id and scope', () => {
  const r = renderLessonsIndex([
    mk(1, { disciplines: ['reservoir'] }), mk(2, { disciplines: [], scope: 'discipline', scope_id: 'geology' }), mk(3, { disciplines: [] }),
    mk(4, { scope: 'project', scope_id: 'orinoco-partnership', disciplines: ['Reservoir'] }), mk(5, { claim: 'Multi\nline   claim.', disciplines: ['geology'] }),
  ], NOW);
  const lines = r.markdown.split('\n');
  const headings = lines.filter(l => l.startsWith('## '));
  assert.deepEqual(headings, ['## geology', '## reservoir', '## general'], 'alphabetical, general last');
  assert.ok(lines.includes(`- Claim number 1 about geology practice. (lesson:${U(1)}, firm)`));
  assert.ok(lines.some(l => l.endsWith(`(lesson:${U(4)}, project:orinoco-partnership)`)));
  assert.ok(lines.some(l => l === `- Multi line claim. (lesson:${U(5)}, firm)`), 'whitespace in a claim is collapsed to one line');
  assert.ok(lines.some(l => l.endsWith(`(lesson:${U(2)}, discipline:geology)`)));
  const geo = lines.slice(lines.indexOf('## geology') + 1, lines.indexOf('## reservoir'));
  assert.equal(geo.filter(l => l.startsWith('- ')).length, 2, 'a discipline-scope lesson groups under its scope_id');
  for (const l of lines.filter(x => x.startsWith('- '))) assert.match(l, LINE);
  assert.equal(r.markdown.endsWith('\n') && !r.markdown.endsWith('\n\n'), true);
});

test('never more than 200 lines: the highest-ranked lessons are kept and the omission is stated', () => {
  const many = Array.from({ length: 400 }, (_, i) => mk(i + 1, { confidence: 0.3 + ((i * 7) % 60) / 100 }));
  const r = renderLessonsIndex(many, NOW);
  assert.ok(r.lines <= INDEX_MAX_LINES, `${r.lines} lines`);
  assert.equal(r.markdown.split('\n').length - 1, r.lines);
  assert.ok(r.omitted > 0 && r.listed + r.omitted === 400);
  assert.match(r.markdown, new RegExp(`_${r.omitted} lower-ranked lessons are not listed; see lessons.json\\._`));
  const listed = new Set([...r.markdown.matchAll(/lesson:([0-9a-f-]{36})/g)].map(m => m[1]));
  assert.equal(listed.size, r.listed);
  const minListed = Math.min(...many.filter(l => listed.has(l.id)).map(l => l.confidence)), maxOmitted = Math.max(...many.filter(l => !listed.has(l.id)).map(l => l.confidence));
  assert.ok(minListed >= maxOmitted - 1e-9, 'everything listed ranks at least as high as everything omitted');
  assert.equal(JSON.parse(r.json).lessons.length, 400, 'lessons.json is not truncated');
  // Exactly at the limit: no omission note.
  const fit = renderLessonsIndex(Array.from({ length: 150 }, (_, i) => mk(i + 1)), NOW);
  assert.ok(fit.lines <= 200 && fit.omitted === 0 && !/not listed/.test(fit.markdown));
});

test('deterministic: the same lessons in any order give identical bytes, with no timestamps', () => {
  const ls = Array.from({ length: 60 }, (_, i) => mk(i + 1, { confidence: 0.5 }));
  const a = renderLessonsIndex(ls, NOW);
  const b = renderLessonsIndex([...ls].reverse(), NOW);
  const c = renderLessonsIndex([...ls].sort((x, y) => x.claim.localeCompare(y.claim)), new Date(NOW.getTime() + 60_000));
  assert.equal(a.markdown, b.markdown); assert.equal(a.json, b.json);
  assert.equal(a.markdown, c.markdown);
  assert.ok(!/20\d\d-\d\d-\d\d/.test(a.markdown), 'no dates in LESSONS.md');
  // Decay reorders within a discipline: a lesson unconfirmed for 13 months lists after an equal fresh one.
  const two = renderLessonsIndex([mk(10, { claim: 'A stale lesson.', disciplines: ['reservoir'], last_confirmed: '2025-08-01T00:00:00Z' }), mk(15, { claim: 'A fresh lesson.', disciplines: ['reservoir'] })], NOW).markdown;
  assert.ok(two.indexOf('A fresh lesson.') < two.indexOf('A stale lesson.'));
});

test('regenerateLessonsIndex lists only confirmed, current, non-confidential lessons and writes only on change', async () => {
  const db = await openDb(undefined); await migrate(db); await seedMaster(db);
  await db.query("INSERT INTO organisations (id,name,kind) VALUES ('acme','Acme','client')");
  await db.query("INSERT INTO legal_tags (id,classification,data_type,client_id,originator) VALUES ('lt-acme','client-nda','second-party','acme','Acme')");
  await db.query("INSERT INTO legal_tags (id,classification,data_type,originator,partners_only) VALUES ('lt-partners','firm','first-party','ATC',true)");
  await db.query("INSERT INTO legal_tags (id,classification,data_type,originator,expires_at) VALUES ('lt-lapsed','firm','first-party','ATC','2026-01-01')");
  for (const l of [
    mk(1), mk(2, { status: 'proposed', last_confirmed: null }), mk(3, { status: 'invalidated', valid_to: '2026-09-01T00:00:00Z' }), mk(4, { legal_tag: 'lt-acme', scope: 'project', scope_id: 'x' }),
    mk(5, { legal_tag: 'lt-partners' }), mk(6, { legal_tag: 'lt-lapsed' }), mk(7, { legal_tag: 'lt-public' }), mk(8, { legal_tag: 'lt-firm', sanitised: true }),
  ]) await insertLesson(db, l);
  const dir = mkdtempSync(path.join(tmpdir(), 'lessons-index-'));
  const r = await regenerateLessonsIndex(db, { now: NOW, dir });
  assert.equal(r.changed, true); assert.equal(r.listed, 3);
  const md = readFileSync(r.markdown_path, 'utf8');
  for (const n of [1, 7, 8]) assert.ok(md.includes(`lesson:${U(n)}`), `lesson ${n} is listed`);
  for (const n of [2, 3, 4, 5, 6]) assert.ok(!md.includes(`lesson:${U(n)}`), `lesson ${n} is not listed`);
  const json = JSON.parse(readFileSync(r.json_path, 'utf8'));
  assert.deepEqual(json.lessons.map((l: any) => l.id).sort(), [U(1), U(7), U(8)]); assert.equal(json.count, 3);
  assert.ok(json.lessons.every((l: any) => l.claim && l.scope && 'confidence' in l));
  // Unchanged content is not rewritten (a bot PR only ever shows real change).
  const t0 = statSync(r.markdown_path).mtimeMs;
  await new Promise(res => setTimeout(res, 20));
  const again = await regenerateLessonsIndex(db, { now: NOW, dir });
  assert.equal(again.changed, false); assert.equal(statSync(r.markdown_path).mtimeMs, t0);
  assert.equal(readFileSync(again.markdown_path, 'utf8'), md);
  // A new confirmation changes it.
  await insertLesson(db, mk(9));
  assert.equal((await regenerateLessonsIndex(db, { now: NOW, dir })).changed, true);
  assert.ok(readFileSync(path.join(dir, 'LESSONS.md'), 'utf8').includes(`lesson:${U(9)}`));
  await db.close();
});
